var translations = {
    xtPharse: 'Passphrase',
    xtPharseConfirm: 'Confirm Passphrase',
    xtPlainTextLabel: 'Secret to Encrypt',
    xtPlainTextLabel2: 'Text for QR',
    xtEncQrData: 'QR Data',
    xtQrLabel: 'QR Label',
    xtQrDescription: 'QR Description',
    xtOptional: '(Optional)',
    xtGenerate: 'Generate',
    xtClearForm: 'Clear Form',
    xtEmbedLabel: 'Embed Label in the QR',
    xtEncrypt: 'Encrypt',
    xtDecrypt: 'Decrypt',
    xtNoEncryption: 'No Encryption',
    xtClose: 'Close',
    xtSaveQr: 'Save QR Image',
    xtPrint: 'Print',
    xtAdjustQrSize: 'QR Size',
    xtErrPharseTooShort: 'The Passphrase too short!',
    xtErrPharseNotMatch: 'The Passphrase does not match the Confirm Passphrase!',
    xtCopyOthers: 'JavaScript copyrights are included in the source.',
    xtNoWarranty: 'No warranty.',
    xtDownloadSource: 'Download from GitHub',
    xtSaveDialogCaption: 'Details',
    xtQrAreaWithDetails: 'QR area with details',
    xtQrImageOnly: 'QR image only',
    xtSaveConfirm: 'Save',
    xtFileName: 'File name',
    xtNotOffline: "It appears this tool is running of a live website, which is not recommended for creating valuable QRs. Instead, use the download link at the bottom of this page to download the ZIP file from GitHub and run this tool offline as a 'local' HTML file.",
    xtHeadTitle: "Client-side (offline) tool for creating AES256 encrypted QR backups",
    xtAbout: "About",

    xhtPlainTextHint: 'Private key(s) or seed(s) or anything to encrypt. Exceeding 1024 characters may result in QR being hard to read by certain software.',
    xhtPharseHint: 'This must be a minimum 5 words (or 25 characters) to call it strong.',
}