var translations = {
    xtPharse: 'Mocne Hasło',
    xtPharseConfirm: 'Potwierdź Hasło',
    xtPlainTextLabel: 'Sekret do zaszyfrowania',
    xtPlainTextLabel2: 'Tekst dla QR',
    xtEncQrData: 'Dane w QR',
    xtQrLabel: 'Etykieta QR',
    xtQrDescription: 'Opis QR',
    xtOptional: '(Opcjonalnie)',
    xtGenerate: 'Generuj',
    xtClearForm: 'Wyczyść Formularz',
    xtEmbedLabel: 'Umieść Etykietę w QR',
    xtEncryption: 'Szyfrowanie',
    xtDecryption: 'Odszyfrowanie',
    xtNoEncryption: 'Bez szyfrowania',
    xtClose: 'Zamknij',
    xtSaveQrImage: 'Zapisz Obraz QR',
    xtSaveQrHtml: 'Zapisz jako HTML',
    xtPrint: 'Drukuj',
    xtAdjustQrSize: 'Rozmiar QR',
    xtErrPharseTooShort: 'Mocne hasło za krótkie!',
    xtErrPharseNotMatch: 'Mocne hasło nie pasuje do Potwierdź Hasło!',
    xtCopyOthers: 'Prawa autorskie JavaScript załączone w kodach źródłowych.',
    xtNoWarranty: 'Bez gwarancji.',
    xtDownloadSource: 'Pobierz z GitHub',
    xtQrAreaWithDetails: 'Obszar QR ze szczegółami',
    xtQrImageOnly: 'Tylko obrazek QR',
    xtSaveConfirm: 'Zapisz',
    xtFileName: 'Nazwa pliku',
    xtNotOffline: "Wygląda na to, że to narzędzie załadowane jest z żywej witryny, nie jest to zalecane do tworzenia cennych QR. Zamiast tego, użyj linku na dole tej strony w celu pobrania pliku ZIP z GitHub i uruchom to narzędzie w trybie offline jako 'lokalny' plik HTML.",
    xtHeadTitle: "Uniwersalny generator QR offline do tworzenia zaszyfrowanych papierowych kopii zapasowych.",
    xtInfo: "Info",
    xtDecrypt: 'Odszyfruj',
    xtEnterEncryptedKey: 'Zaszyfrowane Dane z QR ',
    xtLoadQrImage: 'Załaduj z obrazka QR',
    xtErrWrongPassphrase: "Nie mogę odszyfrować - złe hasło.",
    xtErrGenericDecryptError: "Nie mogę odszyfrować - prawdopodobnie wprowadzony tekst nie jest prawidłowym tekstem zaszyfrowanym AES256 kodowanym w base64",
    xtDecQrData: 'Odszyfrowany Sekret',
    xtDonate: 'Podaruj',
    xtDonationHeader: 'Jeśli uważasz, że to narzędzie jest przydatne, rozważ darowiznę dla autora. Każda darowizna pomoże w utrzymaniu tego narzędzia i oraz w tworzeniu nowych. Dzięki!',
    xtHideDate: 'Ukryj Datę',
    xtQrDateCreatedLabel: 'Utworzono: ',
    xtTwoFactorUtility: '2FA QR',
    xt2faAccountName: 'Nazwa Konta',
    xt2faSecretKey: 'Sekretny Klucz',
    xtErr2FaAccountNameTooShort: 'Nazwa konta zbyt krótka!',
    xtErr2FaSecretKeyNotPresent: 'Wpisz Sekretny Klucz!',
    xt2faPleaseScan: 'Zeskanuj poniższy kod w aplikacji uwierzytelnienia dwuskładnikowego',
    xt2faInfo: 'Jeżeli posiadasz kopię zapasową klucza uwierzytelnienia dwuskładnikowego, to zamiast wpisywać kod do aplikacji 2FA, możesz wkleić go tu i wygenerować kod do szybkiego zeskanowania w dowolnej aplikacji 2FA, na przykład w "Google Authenticator".',
    xtShowPassword: 'Pokaż',
    xtErrEncryptedDataEmpty: 'Wprowadź zaszyfrowane dane',
    xtErrPassphraseEmpty: 'Wprowadź hasło',
    xtErrSecretEmpty: 'Wprowadź sekret, który chcesz zaszyfrować',
    
    xhtPlainTextHint: 'Klucz prywatny lub słowa "seed" lub cokolwiek do zaszyfrowania. Przekroczenie 1024 znaków może spowodować, że QR będzie ciężko odczytać przez niektóre oprogramowanie',
    xhtPharseHint: 'To musi mieć minimum 5 słów (lub 25 znaków) żeby móc nazwać mocnym.',
    xhtEncryptedTextHint: 'Wklej zaszyfrowany tekst z twojego QR, lub kliknij ikonę QR żeby zeskanować, lub załaduj z pliku.',

    xttScanQrHint: 'Zeskanuj kod QR za pomocą kamery',
    xtSelectCamera: 'Wybierz kamerę do zeskanowania QR',
    xtLoadQrFromImage: 'Załaduj zaszyfrowane dane z obrazu QR',
    xtBadQrImage: 'Błąd skanowania pliku, prawdopodobnie nie zawiera obrazu QR lub jest on nie czytelny.',
    xtNoCamerasDetected: 'Nie można wykryć żadnej kamery systemowej lub podłączonej.',
    xtNoCameraPermission: 'Kamera zablokowana przez przeglądarkę. Musisz zezwolić na korzystanie z kamery. Spróbuj ponownie lub sprawdź ustawienia uprawnień przeglądarki, czy nie zostały zablokowane na stałe.',
    xtCameraBusyOrDisconnected: 'Wybrana kamera jest zajęta (używana przez inne oprogramowanie, inną przeglądarkę lub kartę przeglądarki); lub została rozłączona po utworzeniu listy kamer.<br><br>Oryginalny komunikat o błędzie:',
    xtLoadingCameraList: 'Ładowanie listy kamer...',
    xtInitializingCamera: 'Inicjowanie kamery...',

    xtCameraChromeError: 
    "Przeglądarki oparte na Chrome nie pozwalają na dostęp do kamery z lokalizacji file:///.<br>"
    + "Musisz serwować ten plik przez jakiś prosty serwer localhost. Możesz użyć wtyczki \"Web Server for Chrome\"<br>"
    + "https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/<br><br>"
    + "<img src=\"images/webserver.png\"/><br><br>"
    + "Wiele innych opcji na<br>"
    + "https://medium.com/swlh/need-a-local-static-server-here-are-several-options-bbbe77e59a11<br><br>"
    + "Następnie możesz uzyskać dostęp do tego narzędzia lokalnie, np. http://127.0.0.1:8887<br><br>"
    + "Lub poprostu użyj przeglądarki Firefox.",
}