var translations = {
    xtPharse: 'Mocne Hasło',
    xtPharseConfirm: 'Potwierdź Hasło',
    xtPlainTextLabel: 'Sekret do zaszyfrowania',
    xtPlainTextLabel2: 'Tekst dla QR',
    xtEncQrData: 'Dane QR',
    xtQrLabel: 'Etykieta QR',
    xtQrDescription: 'Opis QR',
    xtOptional: '(Opcjonalnie)',
    xtGenerate: 'Generuj',
    xtClearForm: 'Wyczyść Formularz',
    xtEmbedLabel: 'Umieść Etykietę w QR',
    xtEncryption: 'Szyfrowanie',
    xtDecryption: 'Odszyfrowanie',
    xtNoEncryption: 'Bez szyfrowania',
    xtClose: 'Zamknij',
    xtSaveQr: 'Zapisz Obraz QR',
    xtPrint: 'Drukuj',
    xtAdjustQrSize: 'Rozmiar QR',
    xtErrPharseTooShort: 'Mocne hasło za krótkie!',
    xtErrPharseNotMatch: 'Mocne hasło nie pasuje do Potwierdź Hasło!',
    xtCopyOthers: 'Prawa autorskie JavaScript załączone w kodach żródłowych.',
    xtNoWarranty: 'Bez gwarancji.',
    xtDownloadSource: 'Pobierz z GitHub',
    xtSaveDialogCaption: 'Szczegóły',
    xtQrAreaWithDetails: 'Obszar QR ze szczegółami',
    xtQrImageOnly: 'Tylko obrazek QR',
    xtSaveConfirm: 'Zapisz',
    xtFileName: 'Nazwa pliku',
    xtNotOffline: "Wygląda na to, że to narzędzie załadowane jest z żywej witryny, nie jest to zalecane do tworzenia cennych QR. Zamiast tego, użyj linku na dole tej strony w celu pobrania pliku ZIP z GitHub i uruchom to narzędzie w trybie offline jako 'lokalny' plik HTML.",
    xtHeadTitle: "Narzedzie do tworzenia kopii zapasowych w postaci AES256 szyfrowanych QR po stronie klienta (offline)",
    xtAbout: "About",
    xtDecrypt: 'Odszyfruj',
    xtEnterEncryptedKey: 'Zaszyfrowane Dane z QR ',    
    xtLoadQrImage: 'Załaduj z obrazka QR',

    xhtPlainTextHint: 'Klucz prywatny lub słowa "seed" lub cokolwiek do zaszyfrowania. Przekroczenie 1024 znaków może spowodować, że QR będzię ciężko odczytać przez niektóre oprogramowanie',
    xhtPharseHint: 'To musi mieć minumum 5 słow (lub 25 znaków) żeby móc nazwać mocnym.',
    xhtEncryptedKeyHint: 'Wklej zaszyfrowany tekst z twojego QR, lub kliknij ikonę QR żeby zeskanować, lub załaduj z pliku.',
    
    xttScanQrHint: 'Skanuj kod QR',
}