var translations = {
    xtPharse: 'Mocne Hasło',
    xtPharseConfirm: 'Potwierdź Hasło',
    xtPlainTextLabel: 'Sekret do zaszyfrowania',
    xtPlainTextLabel2: 'Tekst dla QR',
    xtEncQrData: 'Dane QR',
    xtQrLabel: 'Etykieta QR',
    xtQrDescription: 'Opis QR',
    xtOptional: '(Opcjonalnie)',
    xtGenerate: 'Generuj',
    xtClearForm: 'Wyczyść Formularz',
    xtEmbedLabel: 'Umieść Etykietę w QR',
    xtEncryption: 'Szyfrowanie',
    xtDecryption: 'Odszyfrowanie',
    xtNoEncryption: 'Bez szyfrowania',
    xtClose: 'Zamknij',
    xtSaveQrImage: 'Zapisz Obraz QR',
    xtSaveQrHtml: 'Zapisz jako HTML',
    xtPrint: 'Drukuj',
    xtAdjustQrSize: 'Rozmiar QR',
    xtErrPharseTooShort: 'Mocne hasło za krótkie!',
    xtErrPharseNotMatch: 'Mocne hasło nie pasuje do Potwierdź Hasło!',
    xtCopyOthers: 'Prawa autorskie JavaScript załączone w kodach żródłowych.',
    xtNoWarranty: 'Bez gwarancji.',
    xtDownloadSource: 'Pobierz z GitHub',
    xtSaveDialogCaption: 'Szczegóły',
    xtQrAreaWithDetails: 'Obszar QR ze szczegółami',
    xtQrImageOnly: 'Tylko obrazek QR',
    xtSaveConfirm: 'Zapisz',
    xtFileName: 'Nazwa pliku',
    xtNotOffline: "Wygląda na to, że to narzędzie załadowane jest z żywej witryny, nie jest to zalecane do tworzenia cennych QR. Zamiast tego, użyj linku na dole tej strony w celu pobrania pliku ZIP z GitHub i uruchom to narzędzie w trybie offline jako 'lokalny' plik HTML.",
    xtHeadTitle: "Uniwersalny Offline Generator QR do Zaszyfrowanych Papierowych Kopii Zapasowych",
    xtInfo: "Info",
    xtDecrypt: 'Odszyfruj',
    xtEnterEncryptedKey: 'Zaszyfrowane Dane z QR ',
    xtLoadQrImage: 'Załaduj z obrazka QR',
    xtErrWrongPassphrase: "Nie mogę odszyfrować - złe hasło.",
    xtErrGenericDecryptError: "Nie mogę odszyfrować - prawdopodobnie wprowadzony text nie jest prawidłowym tekstem zaszyfrowanym AES256 kodowanym w base64",
    xtDecQrData: 'Odszyfrowany Sekret',
    xtDonate: 'Podarój',
    xtDonationHeader: '<b>Jeżeli uważasz, że to jest przydatne narzędzie, rozważ małą daninę do autora. Każda krypto ofiara pomoże w utrzymaniu tego narzędzia oraz w tworzeniu nowych. Dzięki!</b>',
    xtHideDate: 'Ukryj Datę',
    xtQrDateCreatedLabel: 'Utworzono: ',

    xhtPlainTextHint: 'Klucz prywatny lub słowa "seed" lub cokolwiek do zaszyfrowania. Przekroczenie 1024 znaków może spowodować, że QR będzię ciężko odczytać przez niektóre oprogramowanie',
    xhtPharseHint: 'To musi mieć minumum 5 słow (lub 25 znaków) żeby móc nazwać mocnym.',
    xhtEncryptedTextHint: 'Wklej zaszyfrowany tekst z twojego QR, lub kliknij ikonę QR żeby zeskanować, lub załaduj z pliku.',

    xttScanQrHint: 'Skanuj kod QR',
}